package myschool;

import java.awt.HeadlessException;
import java.security.KeyException;
import java.security.KeyManagementException;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.management.openmbean.KeyAlreadyExistsException;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame1.java
 *
 * Created on May 31, 2010, 8:28:09 PM
 */
/**
 *
 * @author Administrator
 */
public class NewJFrame1 extends javax.swing.JFrame {

    public String jtf1;
    public String jtf2;
    public String jtf3;
    public String jtf4;
    public String jtf5;
    public String jtf6;
    public String jtf7;
    public String jtf8;
    public String jtf9;
    public String jtf10;
    public Integer n = 0;

    public  int jtfint1   ;
    public  int   jtfint5;
    public  int   jtfint6;
    public Integer jtfint10;

    /** Creates new form NewJFrame1 */
    public NewJFrame1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        button2 = new java.awt.Button();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("مشخصات دانش آموزان");

        jLabel1.setText("شماره دانش آموزی");

        jLabel2.setText("نام");

        jLabel3.setText("نام خانوادگی");

        jLabel4.setText("نام پدر");

        jLabel5.setText("شماره شناسنامه");

        jLabel6.setText("سال تولد");

        jLabel7.setText("پایه تحصیلی");

        jLabel8.setText("رشته تحصیلی");

        jLabel9.setText("شهر");

        jLabel10.setText("تلفن");

        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        if (n == 1)
        {   jTextField1.setText(null)   ;}

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        jButton1.setText("ثبت");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        label1.setText("*");

        label2.setText("*");

        label3.setText("*");

        label4.setText("*");

        label5.setText("*");

        button2.setLabel("حذف");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        jButton2.setText("پاک کردن");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("تغییر");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("تغییر");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton4)
                                    .addComponent(jButton3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                                    .addComponent(jTextField10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(27, 27, 27)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5)))
                                .addGap(1, 1, 1))
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel9))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))))
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(174, 174, 174)
                                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(166, 166, 166)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jButton1.getAccessibleContext().setAccessibleName("bu");
        button2.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Integer s = JOptionPane.showOptionDialog(null, "are you sure you want insert infromation?", null, WIDTH, WIDTH, null, null, null);

        if (s == 0) {

            jtf1 = jTextField1.getText();
            boolean one = jtf1.equalsIgnoreCase(null);
            one = (jtf1.equalsIgnoreCase("") || one);
            one = (jtf1.equalsIgnoreCase(" ") || one);


            jtf2 = jTextField2.getText();
            boolean two = jtf2.equalsIgnoreCase(null);
            two = (jtf2.equalsIgnoreCase("") || two);
            two = (jtf2.equalsIgnoreCase(" ") || two);



            jtf3 = jTextField3.getText();
            boolean three = jtf3.equalsIgnoreCase(null);
            three = (jtf3.equalsIgnoreCase("") || three);
            three = (jtf3.equalsIgnoreCase(" ") || three);

            jtf7 = jTextField7.getText();
            boolean four = jtf7.equalsIgnoreCase(null);
            four = (jtf7.equalsIgnoreCase("") || four);
            four = (jtf7.equalsIgnoreCase(" ") || four);


            jtf8 = jTextField8.getText();
            boolean five = jtf8.equalsIgnoreCase(null);
            five = (jtf8.equalsIgnoreCase("") || five);
            five = (jtf8.equalsIgnoreCase(" ") || five);



            boolean six = one || two || three || four || five;
            //  six =  six || three   ;
            //  six =  six || four    ;
            // six =  six || five    ;
            // boolean seven = ( one && two && three && four && five  )   ;


         Integer le = jtf1.length()  ;

                     int n = 0 ;
            jtfint6 = Integer.parseInt(jTextField1.getText());
            jtfint10 = Integer.parseInt(jTextField1.getText());


            if (six != false) {
                JOptionPane.showMessageDialog(null, "full * field", null, JOptionPane.INFORMATION_MESSAGE);
            }

            if (six == false) {

                try {

                    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");

                    Connection con = DriverManager.getConnection("jdbc:odbc:mystud");
                    System.out.println("You could connect to database successfully!");
                    Statement stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                    ResultSet upd = stmt.executeQuery("SELECT * FROM studinfo");

                    upd.moveToInsertRow();
                    upd.updateInt("SNUM", Integer.parseInt(jTextField1.getText()));
                    upd.updateString("SNAME", jTextField2.getText());
                    upd.updateString("SLNAME", jTextField3.getText());
                    upd.updateString("SFATHER", jTextField4.getText());
                    upd.updateInt("SSHSH", Integer.parseInt(jTextField5.getText()));
                    upd.updateInt("SBIR", Integer.parseInt(jTextField6.getText()));
                    upd.updateString("SLEVEL", jTextField7.getText());
                    upd.updateString("FIELD", jTextField8.getText());
                    upd.updateString("SCITY", jTextField9.getText());
                   
                    upd.updateInt("SPHONE", Integer.parseInt(jTextField10.getText()));
                    
                    upd.insertRow();

                    JOptionPane.showMessageDialog(null, "transmittal successful", null, JOptionPane.INFORMATION_MESSAGE);




                    upd.close();
                    stmt.close();
                    con.close();



                } catch (ClassNotFoundException  cnfEx) {

                    System.out.println("Unable to load driver!");

                    //  System.exit(1)
                } 

                catch (SQLException  sqlEx) {

                           System.out.println("Cannot connect to database ");
                           JOptionPane.showMessageDialog(null, "Cannot connect to database , ", null, JOptionPane.INFORMATION_MESSAGE);
                    // System.exit(1)  ;


                }

                catch(NumberFormatException  nfe )   {
                 //  System.exit(1)  ;
               JOptionPane.showMessageDialog(null, "check field type", null, JOptionPane.INFORMATION_MESSAGE);


               // System.exit(1)  ;
                } 

            }


        }// end if  s
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1MouseClicked

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
     


try {

                    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");

                    Connection con = DriverManager.getConnection("jdbc:odbc:mystud");
                    System.out.println("You could connect to database successfully!");
                    Statement stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                    
                 ResultSet ser = stmt.executeQuery("select * FROM studinfo where ('" + jTextField1.getText() + "')" );

                  Integer s = JOptionPane.showOptionDialog(null, "are you sure you want  delete it?", null, WIDTH, WIDTH, null, null, null);

                  if(s==0)
                  {

                    int upd = stmt.executeUpdate("delete * FROM studinfo where snum= (" + jTextField1.getText() + ")" );

                  JOptionPane.showMessageDialog(null, "transmittal successful", null, JOptionPane.INFORMATION_MESSAGE);
                  }
                    stmt.close();
                    con.close();



                } catch (ClassNotFoundException  cnfEx) {

                    System.out.println("Unable to load driver!");

                    //  System.exit(1)
                }

                catch (SQLException  sqlEx) {

                           System.out.println("Cannot connect to database ");
                           JOptionPane.showMessageDialog(null, "Cannot connect to database,", null, JOptionPane.INFORMATION_MESSAGE);
                    // System.exit(1)  ;


                }

                catch(NumberFormatException  nfe )   {
                 //  System.exit(1)  ;
               JOptionPane.showMessageDialog(null, "check field type", null, JOptionPane.INFORMATION_MESSAGE);

              

               // System.exit(1)  ;
                }

        
          // TODO add your handling code here:
    }//GEN-LAST:event_button2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        jTextField1.setText(null)   ;
        jTextField2.setText(null)   ;
        jTextField3.setText(null)   ;
        jTextField4.setText(null)   ;
        jTextField5.setText(null)   ;
        jTextField6.setText(null)   ;
        jTextField7.setText(null)   ;
        jTextField8.setText(null)   ;
        jTextField9.setText(null)   ;
        jTextField10.setText(null)  ;


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed



try {
                    Integer s = JOptionPane.showOptionDialog(null, "are you sure you want  change it?", null, WIDTH, WIDTH, null, null, null);


                    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");

                    Connection con = DriverManager.getConnection("jdbc:odbc:mystud");
                    System.out.println("You could connect to database successfully!");
                    Statement stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
               Boolean b = false ;
                    if(s== 0  )
                {
                 stmt.executeUpdate("UPDATE  studinfo   set sname=('" + jTextField2.getText() + "') where  snum =(" + jTextField1.getText() + ")" );
                   //b = stmt.execute("update  studinfo  set sname= ('" + jTextField2.getText() + "')  where snum=(" + jTextField1.getText() + ")" )  ;
                    }
                 if( s == 0 )
                  {

                  JOptionPane.showMessageDialog(null, "transmittal successful", null, JOptionPane.INFORMATION_MESSAGE);
                  }
                    stmt.close();
                    con.close();



                } catch (ClassNotFoundException  cnfEx) {

                    System.out.println("Unable to load driver!");

                    //  System.exit(1)
                }

                catch (SQLException  sqlEx) {

                           System.out.println("Cannot connect to database,check studnumber type ");
                           JOptionPane.showMessageDialog(null, "Cannot connect to database.check studnumber type", null, JOptionPane.INFORMATION_MESSAGE);
                    // System.exit(1)  ;


                }

                catch(NumberFormatException  nfe )   {
                 //  System.exit(1)  ;
               JOptionPane.showMessageDialog(null, "check field type,or key not exist", null, JOptionPane.INFORMATION_MESSAGE);



               // System.exit(1)  ;




        // TODO add your handling code here:
    }

}//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed


try {
                    Integer s = JOptionPane.showOptionDialog(null, "are you sure you want  change it?", null, WIDTH, WIDTH, null, null, null);


                    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");

                    Connection con = DriverManager.getConnection("jdbc:odbc:mystud");
                    System.out.println("You could connect to database successfully!");
                    Statement stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
               Boolean b = false ;
                    if(s== 0  )
                {
                 stmt.executeUpdate("UPDATE  studinfo   set slname=('" + jTextField3.getText() + "') where  snum =(" + jTextField1.getText() + ")" );
                   //b = stmt.execute("update  studinfo  set sname= ('" + jTextField2.getText() + "')  where snum=(" + jTextField1.getText() + ")" )  ;
                    }
                 if( s == 0 )
                  {

                  JOptionPane.showMessageDialog(null, "transmittal successful", null, JOptionPane.INFORMATION_MESSAGE);
                  }
                    stmt.close();
                    con.close();



                } catch (ClassNotFoundException  cnfEx) {

                    System.out.println("Unable to load driver!");

                    //  System.exit(1)
                }

                catch (SQLException  sqlEx) {

                           System.out.println("Cannot connect to database,check studnumber type ");
                           JOptionPane.showMessageDialog(null, "Cannot connect to database.check studnumber type", null, JOptionPane.INFORMATION_MESSAGE);
                    // System.exit(1)  ;


                }

                catch(NumberFormatException  nfe )   {
                 //  System.exit(1)  ;
               JOptionPane.showMessageDialog(null, "check field type,or key not exist", null, JOptionPane.INFORMATION_MESSAGE);


                }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {





        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    // End of variables declaration//GEN-END:variables
}
